package mccool.brendon.cityguess;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    /** Called when the user clicks the New Game button */
    public void startNewGame(View view) {
        Intent intent = new Intent(this, NewGameActivity.class);
        startActivity(intent);
    }

    // Public getter for cities
    public static String getCity(int index) {
        return CITIES[index];
    }

    // List of cities for guessing.  Order is by population decreasing
    // 297 cities
    private static final String[] CITIES = {
            "New York, NY",
            "Los Angeles, California",
            "Chicago, Illinois",
            "Houston, Texas",
            "Philadelphia, Pennsylvania",
            "Phoenix, Arizona",
            "San Antonio, Texas",
            "San Diego, California",
            "Dallas, Texas",
            "San Jose, California",
            "Austin, Texas",
            "Jacksonville, Florida",
            "San Francisco, California",
            "Indianapolis, Indiana",
            "Columbus, Ohio",
            "Fort Worth, Texas",
            "Charlotte, North Carolina",
            "Detroit, Michigan",
            "El Paso, Texas",
            "Seattle, Washington",
            "Denver, Colorado",
            "Washington, District of Columbia",
            "Memphis, Tennessee",
            "Boston, Massachusetts",
            "Nashville, Tennessee",
            "Baltimore, Maryland",
            "Oklahoma City, Oklahoma",
            "Portland, Oregon",
            "Las Vegas, Nevada",
            "Louisville, Kentucky",
            "Milwaukee, Wisconsin",
            "Albuquerque, New Mexico",
            "Tucson, Arizona",
            "Fresno, California",
            "Sacramento, California",
            "Long Beach, California",
            "Kansas City, Missouri",
            "Mesa, Arizona",
            "Atlanta, Georgia",
            "Virginia Beach, Virginia",
            "Omaha, Nebraska",
            "Colorado Springs, Colorado",
            "Raleigh, North Carolina",
            "Miami, Florida",
            "Oakland, California",
            "Minneapolis, Minnesota",
            "Tulsa, Oklahoma",
            "Cleveland, Ohio",
            "Wichita, Kansas",
            "New Orleans, Louisiana",
            "Arlington, Texas",
            "Bakersfield, California",
            "Tampa, Florida",
            "Aurora, Colorado",
            "Honolulu, Hawaii",
            "Anaheim, California",
            "Santa Ana, California",
            "Corpus Christi, Texas",
            "Riverside, California",
            "St. Louis, Missouri",
            "Lexington, Kentucky",
            "Pittsburgh, Pennsylvania",
            "Stockton, California",
            "Anchorage, Alaska",
            "Cincinnati, Ohio",
            "Saint Paul, Minnesota",
            "Greensboro, North Carolina",
            "Toledo, Ohio",
            "Newark, New Jersey",
            "Plano, Texas",
            "Henderson, Nevada",
            "Lincoln, Nebraska",
            "Orlando, Florida",
            "Jersey City, New Jersey",
            "Chula Vista, California",
            "Buffalo, NY",
            "Fort Wayne, Indiana",
            "Chandler, Arizona",
            "St. Petersburg, Florida",
            "Laredo, Texas",
            "Durham, North Carolina",
            "Irvine, California",
            "Madison, Wisconsin",
            "Norfolk, Virginia",
            "Lubbock, Texas",
            "Gilbert, Arizona",
            "Winston–Salem, North Carolina",
            "Glendale, Arizona",
            "Reno, Nevada",
            "Hialeah, Florida",
            "Garland, Texas",
            "Chesapeake, Virginia",
            "Irving, Texas",
            "North Las Vegas, Nevada",
            "Scottsdale, Arizona",
            "Baton Rouge, Louisiana",
            "Fremont, California",
            "Richmond, Virginia",
            "Boise, Idaho",
            "San Bernardino, California",
            "Birmingham, Alabama",
            "Spokane, Washington",
            "Rochester, NY",
            "Modesto, California",
            "Des Moines, Iowa",
            "Oxnard, California",
            "Tacoma, Washington",
            "Fontana, California",
            "Fayetteville, North Carolina",
            "Moreno Valley, California",
            "Columbus, Georgia",
            "Huntington Beach, California",
            "Yonkers, NY",
            "Montgomery, Alabama",
            "Aurora, Illinois",
            "Glendale, California",
            "Shreveport, Louisiana",
            "Akron, Ohio",
            "Little Rock, Arkansas",
            "Amarillo, Texas",
            "Augusta, Georgia",
            "Mobile, Alabama",
            "Grand Rapids, Michigan",
            "Salt Lake City, Utah",
            "Huntsville, Alabama",
            "Tallahassee, Florida",
            "Grand Prairie, Texas",
            "Overland Park, Kansas",
            "Knoxville, Tennessee",
            "Brownsville, Texas",
            "Worcester, Massachusetts",
            "Newport News, Virginia",
            "Santa Clarita, California",
            "Providence, Rhode Island",
            "Fort Lauderdale, Florida",
            "Garden Grove, California",
            "Oceanside, California",
            "Rancho Cucamonga, California",
            "Santa Rosa, California",
            "Port St. Lucie, Florida",
            "Chattanooga, Tennessee",
            "Tempe, Arizona",
            "Jackson, Mississippi",
            "Cape Coral, Florida",
            "Vancouver, Washington",
            "Ontario, California",
            "Sioux Falls, South Dakota",
            "Peoria, Arizona",
            "Springfield, Missouri",
            "Pembroke Pines, Florida",
            "Elk Grove, California",
            "Salem, Oregon",
            "Corona, California",
            "Lancaster, California",
            "Eugene, Oregon",
            "Palmdale, California",
            "McKinney, Texas",
            "Salinas, California",
            "Fort Collins, Colorado",
            "Cary, North Carolina",
            "Hayward, California",
            "Springfield, Massachusetts",
            "Pasadena, Texas",
            "Macon, Georgia",
            "Pomona, California",
            "Alexandria, Virginia",
            "Escondido, California",
            "Sunnyvale, California",
            "Lakewood, Colorado",
            "Kansas City, Kansas",
            "Rockford, Illinois",
            "Torrance, California",
            "Hollywood, Florida",
            "Joliet, Illinois",
            "Bridgeport, Connecticut",
            "Clarksville, Tennessee",
            "Paterson, New Jersey",
            "Naperville, Illinois",
            "Frisco, Texas",
            "Mesquite, Texas",
            "Savannah, Georgia",
            "Syracuse, NY",
            "Dayton, Ohio",
            "Pasadena, California",
            "Orange, California",
            "Fullerton, California",
            "McAllen, Texas",
            "Killeen, Texas",
            "Hampton, Virginia",
            "Bellevue, Washington",
            "Warren, Michigan",
            "Miramar, Florida",
            "West Valley City",
            "Olathe, Kansas",
            "Columbia, South Carolina",
            "Sterling Heights, Michigan",
            "Thornton, Colorado",
            "New Haven, Connecticut",
            "Waco, Texas",
            "Charleston, South Carolina",
            "Thousand Oaks, California",
            "Visalia, California",
            "Cedar Rapids, Iowa",
            "Elizabeth, New Jersey",
            "Roseville, California",
            "Gainesville, Florida",
            "Carrollton, Texas",
            "Stamford, Connecticut",
            "Denton, Texas",
            "Midland, Texas",
            "Coral Springs, Florida",
            "Concord, California",
            "Topeka, Kansas",
            "Simi Valley, California",
            "Surprise, Arizona",
            "Lafayette, Louisiana",
            "Kent, Washington",
            "Hartford, Connecticut",
            "Santa Clara, California",
            "Victorville, California",
            "Abilene, Texas",
            "Murfreesboro, Tennessee",
            "Evansville, Indiana",
            "Vallejo, California",
            "Athens, Georgia",
            "Allentown, Pennsylvania",
            "Berkeley, California",
            "Norman, Oklahoma",
            "Ann Arbor, Michigan",
            "Beaumont, Texas",
            "Independence, Missouri",
            "Columbia, Missouri",
            "Springfield, Illinois",
            "El Monte, California",
            "Fargo, North Dakota",
            "Peoria, Illinois",
            "Provo, Utah",
            "Lansing, Michigan",
            "Odessa, Texas",
            "Downey, California",
            "Wilmington, North Carolina",
            "Arvada, Colorado",
            "Costa Mesa, California",
            "Round Rock, Texas",
            "Carlsbad, California",
            "Miami Gardens, Florida",
            "Westminster, Colorado",
            "Inglewood, California",
            "Rochester, Minnesota",
            "Fairfield, California",
            "Elgin, Illinois",
            "West Jordan, Utah",
            "Clearwater, Florida",
            "Manchester, New Hampshire",
            "Lowell, Massachusetts",
            "Gresham, Oregon",
            "Cambridge, Massachusetts",
            "Ventura, California",
            "Temecula, California",
            "Waterbury, Connecticut",
            "Antioch, California",
            "Billings, Montana",
            "High Point, North Carolina",
            "Richardson, Texas",
            "Richmond, California",
            "West Covina, California",
            "Pueblo, Colorado",
            "Murrieta, California",
            "Centennial, Colorado",
            "Norwalk, California",
            "North Charleston, South Carolina",
            "Everett, Washington",
            "Pompano Beach, Florida",
            "Daly City, California",
            "Palm Bay, Florida",
            "Burbank, California",
            "Wichita Falls, Texas",
            "Boulder, Colorado",
            "Green Bay, Wisconsin",
            "Broken Arrow, Oklahoma",
            "West Palm Beach, Florida",
            "College Station, Texas",
            "Pearland, Texas",
            "Santa Maria, California",
            "El Cajon, California",
            "San Mateo, California",
            "Lewisville, Texas",
            "Rialto, California",
            "Davenport, Iowa",
            "Lakeland, Florida",
            "Clovis, California",
            "Edison, New Jersey",
            "Sandy Springs, Georgia",
            "Tyler, Texas",
            "Las Cruces, New Mexico",
            "South Bend, Indiana",
            "Woodbridge, New Jersey"
    };
}
